name: Deploy my sample website
on: [push]
jobs:
  deploy-sample-website:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."