name: Deploy my sample website
on: [push]
jobs:
  deploy-sample-website:
    runs-on: ubuntu-latest
    steps:
      run: echo "My remote ssh host ip: ${{ vars.REMOTE_HOST_IP }}"
      run: echo "My remote ssh host password: ${{ secrets.SSH_PASS }}"