name: sample work flow file
on:
  push:
    branches:
      - "**"

jobs:
  hello-word:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello world"
  install-python:
    runs-on: ubuntu-latest
    needs:
      - hello-word
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
